config/routes.rb
Rails.application.routes.draw do

  resources :items

  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def new
		@item = Item.new
	end

	def create 
		@item = Item.create(item_params)

		if @item.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def show
		@item = Item.find(params[:id])
	end

	private
		def item_params
			params.require(:item).permit(:name, :value, :category,
										 :date_taken, :due_date, :notes)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item_tile.html.erb
 <% if @items.empty? %>
          <p>Empty list add a new item</p>

      <% else %>
      
      <div class="row">
        <div class="col-md-12">
          <%= link_to "Add New", new_item_path, class: "btn btn-danger" %>
        </div>
      </div>
      <div class="row">
        <div class="owee-tile">

        


          <% @items.each_with_index do |item, index| %>

              <% if index % 4 == 0 %>
                      </div>
                    </div>
                    <hr>

                    <div class="row">
                      <div class="owee-tile">

                          <div class="col-md-3">
                          <%= link_to item do%>
                            <%= image_tag 'max.jpg' %>
                          <% end %>
                          <h4><a href="#"><%= item.name %></a></h4>
                          <p><a href="#"><%= item.category %></a></p>
                          <div class="due">
                           <p><a href="#">Jano</a></p>
                            <p class="pull-rght">Due: <span class="date"><%= item.due_date %></span></p>
                          </div>
                          <div class="pricestat">
                            <p><span class="price pull-left">$<%= item.value %></span></p>
                            <p><span class="status status-lent pull-right">Still Lent</span></p>
                          </div>
                        </div>


              <% else %>

                <div class="col-md-3">
                          
                          <%= link_to item do%>
                            <%= image_tag 'max.jpg' %>
                          <% end %>
                          <h4><a href="#"><%= item.name %></a></h4>
                          <p><a href="#"><%= item.category %></a></p>
                          <div class="due">
                           <p><a href="#">Jano</a></p>
                            <p class="pull-rght">Due: <span class="date"><%= item.due_date %></span></p>
                          </div>
                          <div class="pricestat">
                            <p><span class="price pull-left">$<%= item.value %></span></p>
                            <p><span class="status status-lent pull-right">Still Lent</span></p>
                          </div>
                        </div>

              <% end %>

            <% end %>

          <% end %>

app/views/items/index.html.erb
 <div class="profile-top">
   <div class="container">
          <div class="row">
       <div class="col-md-4 profile-img">
         <%= image_tag "placeholder.gif", class: "img-circle" %>
       </div>
       <div class="col-md-8">
         <h4>User_one <a href="" class="btn btn-default">FOLLOW</a></h4>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis, necessitatibus.</p>
         <div class="row">
           <div class="col-md-6">
             <div class="row">
               <div class="col-md-4"><p><b>289</b> owees</p></div>
               <div class="col-md-4"><p><b>26589</b> hearts</p></div>
               <div class="col-md-4"><p><b>512k </b>followers</p></div>
             </div>

             <div class="row">
               <div class="col-md-2">
                 <a href="#" class="profile-thumbnail"><%= image_tag 'bag.png' %></a>
               </div>

               <div class="col-md-2">
                 <a href="#" class="profile-thumbnail"><%= image_tag 'bag.png' %></a>
               </div>

               <div class="col-md-2">
                 <a href="#" class="profile-thumbnail"><%= image_tag 'bag.png' %></a>
               </div>

               <div class="col-md-2">
                 <a href="#" class="profile-thumbnail"><%= image_tag 'bag.png' %></a>
               </div>

               <div class="col-md-2">
                 <a href="#" class="profile-thumbnail"><%= image_tag 'bag.png' %></a>
               </div>
               <div class="col-md-2">
                 <a href="#" class="profile-thumbnail"><%= image_tag 'bag.png' %></a>
               </div>

             </div>
           </div>

           <div class="col-md-6"></div>
         </div>
       </div>
     </div>
   </div>
 </div>


 <div class="main-content">
    <div class="container">
      
        <%= render "item_tile" %>

        </div>
      </div>
      <hr>

    </div>
  </div>

app/views/items/new.html.erb
<div class="container">

<%= form_for @item, html: {class: "form-horizontal"} do |f| %>

   			<div class="form-group">
   				<%= f.label :name, class: 'control-label col-sm-2' %>
                <div class="col-sm-4">
					<%= f.text_field :name, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
   				<%= f.label :brand, class: 'control-label col-sm-2' %>
                <div class="col-sm-4">
					<%= f.text_field :brand, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
   				<%= f.label :category, class: 'control-label col-sm-2' %>
                <div class="col-sm-4">
					<%= f.text_field :category, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
   				<%= f.label :value, class: 'control-label col-sm-2' %>
                <div class="col-sm-4">
					<%= f.text_field :value, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
   				<%= f.label :date_taken, class: 'control-label col-sm-2' %>
                <div class="col-sm-4">
					<%= f.text_field :date_taken, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
   				<%= f.label :due_date, class: 'control-label col-sm-2' %>
                <div class="col-sm-4">
					<%= f.text_field :due_date, class: 'form-control' %>
                </div>
            </div>

            <div class="form-group">
          <%= f.label :notes, class: 'control-label col-sm-2' %>
                <div class="col-sm-4">
          <%= f.text_area :notes, class: 'form-control' %>
                </div>
            </div>

          


            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <%= f.submit "Create", class: 'btn btn-primary' %>
                </div>
            </div>
<% end %>

</div>

app/views/items/show.html.erb
<div class="container main-show">
     <div class="row">
       <div class="show-left">
       <div class="col-md-3 show-left">
         <%= image_tag 'nike.jpg' %>
         <br><br>
         <h4><%= @item.name %></h4>
         <p>Lent to: <a href="">Jano</a></p>
         <p>Due: <%= @item.due_date %></p>
         <p>Notes: <%= @item.notes %></p>
         <a href="#"><%= @item.category %></a>
       </div>
       </div>
       <div class="col-md-6 show-middle">
         <div class="image-middle">

           <span class="glyphicon glyphicon-chevron-left arrow-left"></span>
           <%= image_tag 'max.jpg', class: "preview-item active-preview" %>
           <%= image_tag 'max2.jpg', class: "preview-item" %>
           <%= image_tag 'max3.jpg', class: "preview-item" %>


         <span class="glyphicon glyphicon-chevron-right arrow-right"></span>
         </div>
         <div class="marker-bottom">
           <%= image_tag 'max-prev.jpg', class: "thumb-prev thumbnail-selected" %>
           <%= image_tag 'max2-prev.jpg', class: "thumb-prev" %>
           <%= image_tag 'max3-prev.jpg', class: "thumb-prev" %>

           
         </div>
       </div>
       <div class="col-md-3">
         <h4><span class="big-price">$<%= @item.value %></span></h4>
         <p class="big-status status-back">Still Lent</p>
       </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reminder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div class="header navbar navbar-default">
    <a href="#" class="navbar-brand">Owee</a>
    <div class="container">
        <div class="collapse navbar-collapse ">
        <ul class="nav navbar-nav pull-left">
             <li><a href="#">Home</a></li>
             <li><a href="#">Contact</a></li>
             <li><a href="#">Help</a></li>
         </ul>

         <ul class="auth pull-right nav navbar-nav">
             <li><a href="#">Profile</a></li>
             <li class="add-item"><a href="#">Add Item</a></li>
             <li><a href="#">Signin</a></li>
             <li><a href="#">Signup</a></li>
         </ul>
        </div>
     </div>
 </div>


<%= yield %>

</body>
</html>